### ISSUE TITLE
Official Stripe library - proper way to implement

### ISSUE THREAD

**Issue by ivanweiler** [Inchoo/magento2-Inchoo_Stripe#1]
We need to see what is proper way to implement official lib in Magento2, respect DI and testability.

**Comment by ivanweiler** [comment]
@udovicic Should we place Stripe lib (https://github.com/stripe/stripe-php) to /vendor/ now with Composer? Is that more preferred now in Magento2? 

https://github.com/stripe/stripe-php/blob/master/composer.json

How do you install extension after Magento2 when "composer install" is required for it ?? Something like
composer require inchoo/stripe:<version> + packagist publish

**Comment by udovicic** [comment]
@ivanweiler In spirit of Magento 2, yes everything should go through composer.

Take a look at [composer branch](https://github.com/Inchoo/magento2-Inchoo_Stripe/tree/composer).
