### ISSUE TITLE
Setup version for module 'Inchoo_Stripe' is not specified"

### ISSUE THREAD

**Issue by cerebrumbr** [Inchoo/magento2-Inchoo_Stripe#4]
Hello Stjepan,

See images.

Return this error.

a:4:{i:0;s:57:"Setup version for module 'Inchoo_Stripe' is not specified";i:1;s:1772:"#0 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Inchoo_Stripe', '1.0')
#1 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(79): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Inchoo_Stripe')
#2 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(55): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#3 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(100): call_user_func_array(Array, Array)
#5 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(124): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#8 /home/magento2ubuntu1404/dados/public_html/ambiente02/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:49:"/public_html/ambiente02/magento2/index.php/admin/";s:11:"script_name";s:42:"/public_html/ambiente02/magento2/index.php";}

![captura de tela de 2015-04-11 13 01 32](https://cloud.githubusercontent.com/assets/2263217/7102063/1477e0fe-e04b-11e4-8f2e-1e5e41f12c17.png)

![captura de tela de 2015-04-11 13 03 06](https://cloud.githubusercontent.com/assets/2263217/7102065/2014c9a4-e04b-11e4-85fa-d09005c2e8ec.png)

Cheers,

Marcelo Amorim

**Comment by udovicic** [comment]
Hi Marcelo,

Thanks for letting me know. It has been a while since I last updated my code here. I'll do it as soon as I can.

Regards

**Comment by cerebrumbr** [comment]
Hello Stjepan,

I await your return.

Thank you very much and best wishes for you.

**Comment by adifucan** [comment]
This error isThe reason of this error is that Magento\Framework\Module\ModuleList\Loader loads full module list information by this path: $dir->search('*/*/etc/module.xml') and your module structure is the following: */*/*/etc/module.xml. As a result it cannot load your module.xml

**Comment by ivanweiler** [comment]
Many things changed in Magento2 since we created this module, since M2 is still in active development. We'll wait a bit more to make sure payment logic is finalized in M2 to avoid major changes and then update Inchoo_Stripe.

**Comment by ivanweiler** [comment]
New version of Inchoo_Stripe is merged to master and it's fully compatible with new checkout in Magento2 1.0.0-beta (merchant beta).
