### ISSUE TITLE
Error on enabling the module

### ISSUE THREAD

**Issue by degaray** [Inchoo/magento2-Inchoo_Stripe#5]
Hi there,
I am trying to install the module on my local environment. I run the environment with a vagrant using rgranadino/mage2_vagrant. I am able to install it using composer, however when I run `bin/magento module:enable Inchoo_Stripe --clear-static-content` I get the following error: "Unknown module(s): 'Inchoo_Stripe'"
Any help will be very appreciated!

**Comment by ivanweiler** [comment]
Hello @degaray ,

We're in the process of testing and making module compatible with Magento 2.0.0 release, we'll update code as soon as possible.

If you want to get your hands dirty :) and test with us, you can check following commit on develop branch to make your installed module work https://github.com/Inchoo/magento2-Inchoo_Stripe/commit/1e7733957efb5e4ab8eb83ca1ddcce756c974202

Basically, you need to add `/app/code/Inchoo/Stripe/registration.php` file, and replace/patch `/app/code/Inchoo/Stripe/Payment.php`. Magento will allow you to enable module after that.

**Comment by cod3gen** [comment]
Hi @ivanweiler 

What do you mean with replace/patch app/code/Inchoo/Stripe/Model/Payment.php ?
I run into same error as @degaray Any help is appreciated :-)

**Comment by ivanweiler** [comment]
We just merged latest changes, this should be fixed now.
